@echo off
title Music Releases - Fetching...
cd /d "D:\AI\Claude Code"
echo.
echo  Fetching new music releases from alterportal.net + coreradio.online...
echo  Please wait...
echo.
"D:\backup\23spi\AppData\Local\Programs\Python\Python310\python.exe" music_releases.py
echo.
echo  Opening report in browser...
start "" "D:\AI\Claude Code\releases.html"
timeout /t 3 >nul
